-- ==============================================
-- RBAC Migration: Role Permissions System
-- Date: 2026-02-11
-- ==============================================

-- 1. Create role_permissions table
CREATE TABLE IF NOT EXISTS `role_permissions` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `role` VARCHAR(20) NOT NULL COMMENT 'superroot, root, admin, operator',
    `page_key` VARCHAR(100) NOT NULL COMMENT 'e.g. organization.company',
    `can_view` TINYINT(1) NOT NULL DEFAULT 0,
    `can_create` TINYINT(1) NOT NULL DEFAULT 0,
    `can_edit` TINYINT(1) NOT NULL DEFAULT 0,
    `can_delete` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `unique_role_page` (`role`, `page_key`),
    INDEX `idx_role` (`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Update user roles
UPDATE users SET role = 'superroot' WHERE email = 'root@smartcms.local';
UPDATE users SET role = 'root' WHERE email = 'superadmin@smartcms.local';
UPDATE users SET role = 'admin' WHERE email = 'cmsadmin@smartx.local';
UPDATE users SET role = 'admin' WHERE email = 'admin@smartx.local';

-- 3. Insert default permissions for SUPERROOT (full access to everything)
INSERT INTO role_permissions (role, page_key, can_view, can_create, can_edit, can_delete) VALUES
('superroot', 'dashboard', 1, 1, 1, 1),
('superroot', 'organization.company', 1, 1, 1, 1),
('superroot', 'organization.head_office', 1, 1, 1, 1),
('superroot', 'organization.branch', 1, 1, 1, 1),
('superroot', 'organization.sub_branch', 1, 1, 1, 1),
('superroot', 'organization.connectivity_diagram', 1, 1, 1, 1),
('superroot', 'connectivity.lines', 1, 1, 1, 1),
('superroot', 'connectivity.extensions', 1, 1, 1, 1),
('superroot', 'connectivity.private_wire', 1, 1, 1, 1),
('superroot', 'connectivity.cas', 1, 1, 1, 1),
('superroot', 'connectivity.intercoms', 1, 1, 1, 1),
('superroot', 'connectivity.call_routing', 1, 1, 1, 1),
('superroot', 'connectivity.trunk', 1, 1, 1, 1),
('superroot', 'connectivity.inbound', 1, 1, 1, 1),
('superroot', 'connectivity.outbound', 1, 1, 1, 1),
('superroot', 'connectivity.conference', 1, 1, 1, 1),
('superroot', 'sbc.sbc', 1, 1, 1, 1),
('superroot', 'sbc.connection', 1, 1, 1, 1),
('superroot', 'sbc.routing', 1, 1, 1, 1),
('superroot', 'sbc.status_monitor', 1, 1, 1, 1),
('superroot', 'turret.users', 1, 1, 1, 1),
('superroot', 'turret.templates', 1, 1, 1, 1),
('superroot', 'turret.groups', 1, 1, 1, 1),
('superroot', 'turret.policies', 1, 1, 1, 1),
('superroot', 'turret.phone_directory', 1, 1, 1, 1),
('superroot', 'cms_admin.user_management', 1, 1, 1, 1),
('superroot', 'cms_admin.group', 1, 1, 1, 1),
('superroot', 'cms_admin.policy_privilege', 1, 1, 1, 1),
('superroot', 'cms_admin.layout_customizer', 1, 1, 1, 1),
('superroot', 'logs.system_log', 1, 1, 1, 1),
('superroot', 'logs.activity_log', 1, 1, 1, 1),
('superroot', 'logs.call_log', 1, 1, 1, 1),
('superroot', 'logs.alarm_notification', 1, 1, 1, 1),
('superroot', 'network.static_route', 1, 1, 1, 1),
('superroot', 'network.firewall', 1, 1, 1, 1),
('superroot', 'backup', 1, 1, 1, 1);

-- 4. ROOT permissions (full access except policy page)
INSERT INTO role_permissions (role, page_key, can_view, can_create, can_edit, can_delete) VALUES
('root', 'dashboard', 1, 1, 1, 1),
('root', 'organization.company', 1, 1, 1, 1),
('root', 'organization.head_office', 1, 1, 1, 1),
('root', 'organization.branch', 1, 1, 1, 1),
('root', 'organization.sub_branch', 1, 1, 1, 1),
('root', 'organization.connectivity_diagram', 1, 1, 1, 1),
('root', 'connectivity.lines', 1, 1, 1, 1),
('root', 'connectivity.extensions', 1, 1, 1, 1),
('root', 'connectivity.private_wire', 1, 1, 1, 1),
('root', 'connectivity.cas', 1, 1, 1, 1),
('root', 'connectivity.intercoms', 1, 1, 1, 1),
('root', 'connectivity.call_routing', 1, 1, 1, 1),
('root', 'connectivity.trunk', 1, 1, 1, 1),
('root', 'connectivity.inbound', 1, 1, 1, 1),
('root', 'connectivity.outbound', 1, 1, 1, 1),
('root', 'connectivity.conference', 1, 1, 1, 1),
('root', 'sbc.sbc', 1, 1, 1, 1),
('root', 'sbc.connection', 1, 1, 1, 1),
('root', 'sbc.routing', 1, 1, 1, 1),
('root', 'sbc.status_monitor', 1, 1, 1, 1),
('root', 'turret.users', 1, 1, 1, 1),
('root', 'turret.templates', 1, 1, 1, 1),
('root', 'turret.groups', 1, 1, 1, 1),
('root', 'turret.policies', 1, 1, 1, 1),
('root', 'turret.phone_directory', 1, 1, 1, 1),
('root', 'cms_admin.user_management', 1, 1, 1, 1),
('root', 'cms_admin.group', 1, 1, 1, 1),
('root', 'cms_admin.policy_privilege', 1, 1, 1, 0),
('root', 'cms_admin.layout_customizer', 1, 1, 1, 0),
('root', 'logs.system_log', 1, 0, 0, 0),
('root', 'logs.activity_log', 1, 0, 0, 0),
('root', 'logs.call_log', 1, 0, 0, 0),
('root', 'logs.alarm_notification', 1, 0, 0, 0),
('root', 'network.static_route', 1, 1, 1, 1),
('root', 'network.firewall', 1, 1, 1, 1),
('root', 'backup', 1, 1, 1, 0);

-- 5. ADMIN permissions (view + create + edit, limited delete)
INSERT INTO role_permissions (role, page_key, can_view, can_create, can_edit, can_delete) VALUES
('admin', 'dashboard', 1, 0, 0, 0),
('admin', 'organization.company', 1, 0, 0, 0),
('admin', 'organization.head_office', 1, 1, 1, 0),
('admin', 'organization.branch', 1, 1, 1, 0),
('admin', 'organization.sub_branch', 1, 1, 1, 0),
('admin', 'organization.connectivity_diagram', 1, 0, 0, 0),
('admin', 'connectivity.lines', 1, 1, 1, 0),
('admin', 'connectivity.extensions', 1, 1, 1, 0),
('admin', 'connectivity.private_wire', 1, 1, 1, 0),
('admin', 'connectivity.cas', 1, 1, 1, 0),
('admin', 'connectivity.intercoms', 1, 1, 1, 0),
('admin', 'connectivity.call_routing', 1, 0, 0, 0),
('admin', 'connectivity.trunk', 1, 1, 1, 0),
('admin', 'connectivity.inbound', 1, 1, 1, 0),
('admin', 'connectivity.outbound', 1, 1, 1, 0),
('admin', 'connectivity.conference', 1, 1, 1, 0),
('admin', 'sbc.sbc', 1, 0, 0, 0),
('admin', 'sbc.connection', 1, 0, 0, 0),
('admin', 'sbc.routing', 1, 0, 0, 0),
('admin', 'sbc.status_monitor', 1, 0, 0, 0),
('admin', 'turret.users', 1, 1, 1, 0),
('admin', 'turret.templates', 1, 0, 0, 0),
('admin', 'turret.groups', 1, 1, 1, 0),
('admin', 'turret.policies', 1, 0, 0, 0),
('admin', 'turret.phone_directory', 1, 1, 1, 0),
('admin', 'cms_admin.user_management', 0, 0, 0, 0),
('admin', 'cms_admin.group', 0, 0, 0, 0),
('admin', 'cms_admin.policy_privilege', 0, 0, 0, 0),
('admin', 'cms_admin.layout_customizer', 0, 0, 0, 0),
('admin', 'logs.system_log', 1, 0, 0, 0),
('admin', 'logs.activity_log', 1, 0, 0, 0),
('admin', 'logs.call_log', 1, 0, 0, 0),
('admin', 'logs.alarm_notification', 1, 0, 0, 0),
('admin', 'network.static_route', 0, 0, 0, 0),
('admin', 'network.firewall', 0, 0, 0, 0),
('admin', 'backup', 0, 0, 0, 0);

-- 6. OPERATOR permissions (mostly view-only)
INSERT INTO role_permissions (role, page_key, can_view, can_create, can_edit, can_delete) VALUES
('operator', 'dashboard', 1, 0, 0, 0),
('operator', 'organization.company', 1, 0, 0, 0),
('operator', 'organization.head_office', 1, 0, 0, 0),
('operator', 'organization.branch', 1, 0, 0, 0),
('operator', 'organization.sub_branch', 1, 0, 0, 0),
('operator', 'organization.connectivity_diagram', 1, 0, 0, 0),
('operator', 'connectivity.lines', 1, 0, 0, 0),
('operator', 'connectivity.extensions', 1, 0, 0, 0),
('operator', 'connectivity.private_wire', 1, 0, 0, 0),
('operator', 'connectivity.cas', 1, 0, 0, 0),
('operator', 'connectivity.intercoms', 1, 0, 0, 0),
('operator', 'connectivity.call_routing', 0, 0, 0, 0),
('operator', 'connectivity.trunk', 1, 0, 0, 0),
('operator', 'connectivity.inbound', 0, 0, 0, 0),
('operator', 'connectivity.outbound', 0, 0, 0, 0),
('operator', 'connectivity.conference', 1, 0, 0, 0),
('operator', 'sbc.sbc', 0, 0, 0, 0),
('operator', 'sbc.connection', 0, 0, 0, 0),
('operator', 'sbc.routing', 0, 0, 0, 0),
('operator', 'sbc.status_monitor', 0, 0, 0, 0),
('operator', 'turret.users', 0, 0, 0, 0),
('operator', 'turret.templates', 0, 0, 0, 0),
('operator', 'turret.groups', 0, 0, 0, 0),
('operator', 'turret.policies', 0, 0, 0, 0),
('operator', 'turret.phone_directory', 1, 0, 0, 0),
('operator', 'cms_admin.user_management', 0, 0, 0, 0),
('operator', 'cms_admin.group', 0, 0, 0, 0),
('operator', 'cms_admin.policy_privilege', 0, 0, 0, 0),
('operator', 'cms_admin.layout_customizer', 0, 0, 0, 0),
('operator', 'logs.system_log', 0, 0, 0, 0),
('operator', 'logs.activity_log', 0, 0, 0, 0),
('operator', 'logs.call_log', 1, 0, 0, 0),
('operator', 'logs.alarm_notification', 0, 0, 0, 0),
('operator', 'network.static_route', 0, 0, 0, 0),
('operator', 'network.firewall', 0, 0, 0, 0),
('operator', 'backup', 0, 0, 0, 0);
