import { Routes } from '@angular/router';
import { AuthGuard } from '../../auth.guard';

export const CONNECTIVITY_ROUTES: Routes = [
    {
        path: 'call-servers',
        loadComponent: () => import('./call-servers').then((d) => d.CallServersComponent),
        data: { title: 'Call Servers | SmartUCX', pageKey: 'connectivity.call_server' },
        canActivate: [AuthGuard],
    },
    {
        path: 'lines',
        loadComponent: () => import('./lines').then((d) => d.LinesComponent),
        data: { title: 'Lines | SmartUCX', pageKey: 'connectivity.lines' },
        canActivate: [AuthGuard],
    },
    {
        path: 'extensions',
        loadComponent: () => import('./extensions').then((d) => d.ExtensionsComponent),
        data: { title: 'Extensions | SmartUCX', pageKey: 'connectivity.extensions' },
        canActivate: [AuthGuard],
    },
    {
        path: 'vpw',
        loadComponent: () => import('./vpw').then((d) => d.VPWComponent),
        data: { title: 'VPW | SmartUCX', pageKey: 'connectivity.vpw' },
        canActivate: [AuthGuard],
    },
    {
        path: 'cas',
        loadComponent: () => import('./cas').then((d) => d.CASComponent),
        data: { title: 'CAS | SmartUCX', pageKey: 'connectivity.cas' },
        canActivate: [AuthGuard],
    },
    {
        path: 'sip-3rd-party',
        loadComponent: () => import('./sip-3rd-party').then((d) => d.Sip3rdPartyComponent),
        data: { title: 'SIP/3rd Party Line | SmartUCX', pageKey: 'connectivity.sip_3rd_party' },
        canActivate: [AuthGuard],
    },
    {
        path: 'private-wire',
        loadComponent: () => import('./private-wire').then((d) => d.PrivateWireComponent),
        data: { title: 'Private Wire | SmartUCX', pageKey: 'connectivity.private_wire' },
        canActivate: [AuthGuard],
    },
    {
        path: 'trunk',
        loadComponent: () => import('./trunk').then((d) => d.TrunkComponent),
        data: { title: 'Trunk | SmartUCX', pageKey: 'connectivity.trunk' },
        canActivate: [AuthGuard],
    },
    {
        path: 'intercoms',
        loadComponent: () => import('./intercoms').then((d) => d.IntercomsComponent),
        data: { title: 'Intercom | SmartUCX', pageKey: 'connectivity.intercoms' },
        canActivate: [AuthGuard],
    },
    {
        path: 'call-routing',
        loadComponent: () => import('./call-routing').then((d) => d.CallRoutingComponent),
        data: { title: 'Call Routing | SmartUCX', pageKey: 'connectivity.call_routing' },
        canActivate: [AuthGuard],
    },
    {
        path: 'call-routing/inbound',
        loadComponent: () => import('./inbound-routing').then((d) => d.InboundRoutingComponent),
        data: { title: 'Inbound Routing | SmartUCX', pageKey: 'connectivity.inbound' },
        canActivate: [AuthGuard],
    },
    {
        path: 'call-routing/outbound',
        loadComponent: () => import('./outbound-routing').then((d) => d.OutboundRoutingComponent),
        data: { title: 'Outbound Routing | SmartUCX', pageKey: 'connectivity.outbound' },
        canActivate: [AuthGuard],
    },
    {
        path: 'sbc',
        loadComponent: () => import('./sbc').then((d) => d.SBCComponent),
        data: { title: 'SBC | SmartUCX', pageKey: 'sbc.sbc' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/ivr',
        loadComponent: () => import('./ivr-list').then((d) => d.IvrListComponent),
        data: { title: 'IVR | SmartUCX', pageKey: 'connectivity.ivr' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/black-list',
        loadComponent: () => import('./black-list').then((d) => d.BlackListComponent),
        data: { title: 'Black List | SmartUCX', pageKey: 'connectivity.black_list' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/conference',
        loadComponent: () => import('./conference').then((d) => d.ConferenceComponent),
        data: { title: 'Conference | SmartUCX', pageKey: 'connectivity.conference' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/customs-destination',
        loadComponent: () => import('./custom-destination').then((d) => d.CustomDestinationComponent),
        data: { title: 'Custom Destination | SmartUCX', pageKey: 'connectivity.custom_destination' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/misc-destination',
        loadComponent: () => import('./misc-destination').then((d) => d.MiscDestinationComponent),
        data: { title: 'Misc Destination | SmartUCX', pageKey: 'connectivity.misc_destination' },
        canActivate: [AuthGuard],
    },
    {
        path: 'sbc-connections',
        loadComponent: () => import('./sbc-connections').then((d) => d.SBCConnectionsComponent),
        data: { title: 'SBC Connections | SmartUCX', pageKey: 'sbc.connection' },
        canActivate: [AuthGuard],
    },
    {
        path: 'sbc-routing',
        loadComponent: () => import('./sbc-routing').then((d) => d.SBCRoutingComponent),
        data: { title: 'SBC Routing | SmartUCX', pageKey: 'sbc.routing' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/broadcast',
        loadComponent: () => import('./broadcast').then((d) => d.BroadcastComponent),
        data: { title: 'Broadcast | SmartUCX', pageKey: 'connectivity.broadcast' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/music-on-hold',
        loadComponent: () => import('./music-on-hold').then((d) => d.MusicOnHoldComponent),
        data: { title: 'Music on Hold | SmartUCX', pageKey: 'connectivity.music_on_hold' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/paging-intercom',
        loadComponent: () => import('./paging-intercom').then((d) => d.PagingIntercomComponent),
        data: { title: 'Paging & Intercom | SmartUCX', pageKey: 'connectivity.paging_intercom' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/recording',
        loadComponent: () => import('./recording').then((d) => d.RecordingComponent),
        data: { title: 'Recording | SmartUCX', pageKey: 'connectivity.recording' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/ring-group',
        loadComponent: () => import('./ring-group').then((d) => d.RingGroupComponent),
        data: { title: 'Ring Group | SmartUCX', pageKey: 'connectivity.ring_group' },
        canActivate: [AuthGuard],
    },
    {
        path: 'feature/time-conditions',
        loadComponent: () => import('./time-conditions').then((d) => d.TimeConditionsComponent),
        data: { title: 'Time Conditions | SmartUCX', pageKey: 'connectivity.time_conditions' },
        canActivate: [AuthGuard],
    },
    {
        path: 'sbc-status-monitor',
        loadComponent: () => import('./sbc-status-monitor').then((d) => d.SBCStatusMonitorComponent),
        data: { title: 'SBC Status Monitor | SmartUCX', pageKey: 'sbc.status_monitor' },
        canActivate: [AuthGuard],
    },
];
